-- Add human_readable_title column to checks table
-- This will store AI-generated natural language titles for violations
-- Example: "Latchside clearance too small" instead of "ICC:CBC_Chapter11A_11B:2025:CA:11B-404.2.6"

ALTER TABLE checks
ADD COLUMN IF NOT EXISTS human_readable_title TEXT;

COMMENT ON COLUMN checks.human_readable_title IS 'AI-generated natural language title for violations (e.g., "Bathroom door too narrow"). Generated by GPT-4o-mini.';
